export const ADD_FEED = 'ADD_FEED'
export const IMPORT_FEEDS = 'IMPORT_FEEDS'
export const GET_FEEDS_UNREAD = 'GET_FEEDS_UNREAD'
export const GET_FEED = 'GET_FEED'
export const SHOW_FEED = 'SHOW_FEED'
